env:
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - 'eslint-plugin-hapi'
rules:
  no-console: 'off'
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always