env:
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  no-var: 'error'
  eqeqeq: 'error'
  no-console: 'off'
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always