#
# Collections for content articles
#
collections:
    best_practices:
    getting_started:
    key_concepts:
    overview:
    prerequisites:
    recipes:
    references:
        output: true
        permalink: /reference/:path/
    testing:
    tools:
    typical_scenarios:
    updates:

baseurl:
name: PlayerPro
logo: /assets/local/images/project_logo.png
slack_url: https://spandigital.slack.com/messages/player-pro/
slack_channel: player-pro

#
# Exclude the following files from the generated site
#
exclude: [
    "README.md",
    "LICENSE",
    "_TEMPLATE.md",
    ".gitignore",
]

#
# System wide defaults
#
defaults:
    -
        scope:
            path: ""
        values:
            logo: ""
            layout: "default"
            github-url: "https://github.com/"
