# -------------------------------------------------
# Configuration for a solution documentation system
# -------------------------------------------------

#
# Collections for content articles
#
collections:
    - best_practices
    - recipes
    - tools
    - typical_scenarios
    - reference_articles
    - updates

baseurl:
#url: http://localhost:4000/
exclude: ["README.md", "LICENSE", ".gitignore"]
#
# Code highlighter pygments requires python
#
highlighter: pygments

defaults:
    -
        scope:
            path: "" # site wide
        values:
            layout: "documentation-page"
            github-url: "https://github.com/"
            label-id: "overide-in-each-article"  # This is a workaround because nether label or id are in scope of a collection