# -------------------------------------------------
# Configuration for a solution documentation system
# -------------------------------------------------

#
# Collections for content articles
#
collections:
    best_practices:
    getting_started:
    key_concepts:
    overview:
    prerequisites:
    recipes:
    references:
        output: true
        permalink: /reference/:path/
    testing:
    tools:
    typical_scenarios:
    updates:

baseurl:
#url: http://localhost:4000/
portalurl: http://localhost:4000
#
# use redcarpet as the Markdown processor. Make it like GFM - Github Flavored Markdwn
# redcarpet must be installed locally for this to work "$sudo gem install redcarpet"
# set highlighter to whatever you want...
#
markdown: redcarpet
redcarpet:
    extensions: [ fenced_code_blocks, no_intra_emphasis, tables, autolink, strikethrough ]
highlighter: pygments

#
# Exclude the following files from the generated site
#
exclude: [
    "README.md",
    "LICENSE",
    "_TEMPLATE.md",
    ".gitignore",
]

#
# System wide defaults
#
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            github-url: "https://github.com/"