# -------------------------------------------------
# Configuration for a solution documentation system
# -------------------------------------------------

#
# Collections for content articles
#
collections:
    best_practices:
    getting_started:
    key_concepts:
    overview:
    prerequisites:
    recipes:
    references:
        output: true
        permalink: /reference/:path/
    testing:
    tools:
    typical_scenarios:
    updates:

baseurl:
#url: http://localhost:4000/
portalurl: http://localhost:4000

markdown: redcarpet
highlighter: null

#
# Exclude the following files from the generated site
#
exclude: [
    "README.md",
    "LICENSE",
    "_TEMPLATE.md",
    ".gitignore",
]

#
# System wide defaults
#
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            github-url: "https://github.com/"