# =============================================================================
# Configuration for a solution documentation system
# =============================================================================


# ------------------------------------------------------------[ Collections ]--
collections:
    contribution:
    best_practices:
    getting_started:
    key_concepts:
    overview:
    prerequisites:
    cookbook:
    references:
        output: true
        permalink: /reference/:path/
    tools:
    typical_scenarios:
    updates:


# ------------------------------------------------------[ URL Configuration ]--
baseurl:
#url: http://localhost:4000/


# ---------------------------------------------------------------[ Excludes ]--
exclude: [
    "README.md",
    "LICENSE",
    ".gitignore"
]


# ------------------------------------------------------[ Code Highlighting ]--
highlighter: pygments


# ---------------------------------------------------------------[ Defaults ]--
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            github-url: "https://github.com/"
